# Generated by Django 2.1.4 on 2019-10-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emproll', models.IntegerField()),
                ('empname', models.CharField(max_length=60)),
                ('empdob', models.DateField()),
                ('empmail', models.EmailField(max_length=254)),
                ('phonenum', models.IntegerField()),
                ('empaddr', models.TextField()),
            ],
        ),
    ]
