# Generated by Django 2.1.4 on 2019-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empdetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phonenum',
            field=models.IntegerField(verbose_name=11),
        ),
    ]
